# Generated by Django 4.1.2 on 2023-01-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_category_slug_alter_category_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Yayınlandı"),
                    ("draft", "Taslak"),
                    ("deleted", "Silindi"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("Yes", "Evet"), ("No", "Hayır"), ("draft", "Taslak")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Yayınlandı"),
                    ("draft", "Taslak"),
                    ("deleted", "Silindi"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[("Yes", "Evet"), ("No", "Hayır"), ("draft", "Taslak")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Yayınlandı"),
                    ("draft", "Taslak"),
                    ("deleted", "Silindi"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="status",
            field=models.CharField(
                choices=[("Yes", "Evet"), ("No", "Hayır"), ("draft", "Taslak")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="status",
            field=models.CharField(
                choices=[("Yes", "Evet"), ("No", "Hayır"), ("draft", "Taslak")],
                default="draft",
                max_length=12,
            ),
        ),
    ]
