# Generated by Django 4.1.2 on 2023-01-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_product_brand_alter_category_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Yayınlandı"),
                    ("deleted", "Silindi"),
                    ("draft", "Taslak"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Yayınlandı"),
                    ("deleted", "Silindi"),
                    ("draft", "Taslak"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Yayınlandı"),
                    ("deleted", "Silindi"),
                    ("draft", "Taslak"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
    ]
