# Generated by Django 4.1.2 on 2023-02-01 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_category_level_category_lft_category_rght_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="base.product",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="rating",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
