# Generated by Django 4.1.2 on 2023-02-01 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_shop_product_alter_shop_rating"),
    ]

    operations = [
        migrations.RemoveField(model_name="shop", name="product",),
        migrations.AddField(
            model_name="product",
            name="product",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop",
                to="base.shop",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Taslak"),
                    ("published", "Yayınlandı"),
                    ("deleted", "Silindi"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("No", "Hayır"), ("draft", "Taslak"), ("Yes", "Evet")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Taslak"),
                    ("published", "Yayınlandı"),
                    ("deleted", "Silindi"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[("No", "Hayır"), ("draft", "Taslak"), ("Yes", "Evet")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Taslak"),
                    ("published", "Yayınlandı"),
                    ("deleted", "Silindi"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="status",
            field=models.CharField(
                choices=[("No", "Hayır"), ("draft", "Taslak"), ("Yes", "Evet")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="status",
            field=models.CharField(
                choices=[("No", "Hayır"), ("draft", "Taslak"), ("Yes", "Evet")],
                default="draft",
                max_length=12,
            ),
        ),
    ]
