# Generated by Django 4.1.2 on 2023-02-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_remove_shop_product_product_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Yayınlandı"),
                    ("deleted", "Silindi"),
                    ("draft", "Taslak"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("draft", "Taslak"), ("No", "Hayır"), ("Yes", "Evet")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Yayınlandı"),
                    ("deleted", "Silindi"),
                    ("draft", "Taslak"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[("draft", "Taslak"), ("No", "Hayır"), ("Yes", "Evet")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Yayınlandı"),
                    ("deleted", "Silindi"),
                    ("draft", "Taslak"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="status",
            field=models.CharField(
                choices=[("draft", "Taslak"), ("No", "Hayır"), ("Yes", "Evet")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="status",
            field=models.CharField(
                choices=[("draft", "Taslak"), ("No", "Hayır"), ("Yes", "Evet")],
                default="draft",
                max_length=12,
            ),
        ),
    ]
