# Generated by Django 4.1.2 on 2023-02-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_category_status_alter_comment_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="product", new_name="shop",
        ),
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[
                    ("deleted", "Silindi"),
                    ("published", "Yayınlandı"),
                    ("draft", "Taslak"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("Yes", "Evet"), ("draft", "Taslak"), ("No", "Hayır")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="status",
            field=models.CharField(
                choices=[
                    ("deleted", "Silindi"),
                    ("published", "Yayınlandı"),
                    ("draft", "Taslak"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[("Yes", "Evet"), ("draft", "Taslak"), ("No", "Hayır")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("deleted", "Silindi"),
                    ("published", "Yayınlandı"),
                    ("draft", "Taslak"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="status",
            field=models.CharField(
                choices=[("Yes", "Evet"), ("draft", "Taslak"), ("No", "Hayır")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="status",
            field=models.CharField(
                choices=[("Yes", "Evet"), ("draft", "Taslak"), ("No", "Hayır")],
                default="draft",
                max_length=12,
            ),
        ),
    ]
