# Generated by Django 4.1.2 on 2023-02-03 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_rename_product_product_shop_alter_category_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Yayınlandı"),
                    ("draft", "Taslak"),
                    ("deleted", "Silindi"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("Yes", "Evet"), ("No", "Hayır"), ("draft", "Taslak")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Yayınlandı"),
                    ("draft", "Taslak"),
                    ("deleted", "Silindi"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[("Yes", "Evet"), ("No", "Hayır"), ("draft", "Taslak")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Yayınlandı"),
                    ("draft", "Taslak"),
                    ("deleted", "Silindi"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="status",
            field=models.CharField(
                choices=[("Yes", "Evet"), ("No", "Hayır"), ("draft", "Taslak")],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="image",
            field=models.ImageField(
                blank=True, default="images/", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="rating",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="status",
            field=models.CharField(
                choices=[("Yes", "Evet"), ("No", "Hayır"), ("draft", "Taslak")],
                default="draft",
                max_length=12,
            ),
        ),
    ]
